# Blog settings
#permalink: /blog/:title
permalink: /blog/:title

# My variables
name: Baremetallics
description: Learning this thing called  embedded systems
url: https://baremetallics.com
locale: en-US
google_verification: null

# Social Media
# twitter_username: baremetallics 
#facebook_username: Baremetallics-113402556954726 
#instagram_username: baremetallics

# Google services
#google_analytics: UA-147073620-4

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

gems:
  - jekyll-seo-tag

future: false

plugins: [jekyll-paginate]

paginate: 10
paginate_path: "/programming/page/:num/"

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Talkyard - Comments
talkyard_server_url: https://comments-for-baremetallics-com.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

page_gen:
  - data: books
    name: key
    dir: goto
    extention: html
